In [2]:
import pandas as pd

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv')

In [6]:
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [7]:
import numpy as np

In [8]:
# Creating arrays

In [13]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [14]:
np.linspace(0,1,22)

array([0.        , 0.04761905, 0.0952381 , 0.14285714, 0.19047619,
       0.23809524, 0.28571429, 0.33333333, 0.38095238, 0.42857143,
       0.47619048, 0.52380952, 0.57142857, 0.61904762, 0.66666667,
       0.71428571, 0.76190476, 0.80952381, 0.85714286, 0.9047619 ,
       0.95238095, 1.        ])

In [ ]:
# Multi Dimentional Arrays

In [15]:
np.zeros((4,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [16]:
# Randomly generated Arrays

In [17]:
np.random.rand(4,3)

array([[0.2655153 , 0.32861308, 0.1383645 ],
       [0.69911074, 0.81460196, 0.09240775],
       [0.78098168, 0.90098357, 0.74578087],
       [0.80468866, 0.58557148, 0.43057476]])

In [18]:
# Element-wise operations

In [20]:
a = np.arange(3)
a

array([0, 1, 2])

In [21]:
a + 1

array([1, 2, 3])

In [22]:
# comparison operators

In [23]:
a >= 2

array([False, False,  True])

In [24]:
# Summarizing Operators

In [25]:
a

array([0, 1, 2])

In [26]:
a.max()

np.int64(2)

In [27]:
a.mean()

np.float64(1.0)

In [28]:
a.std()

np.float64(0.816496580927726)